version: '3.4'
services:

  app:
    build:
      context: ./app
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - netw
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: database.Dockerfile
    ports:
      - "5432:5432"
    networks:
      - netw

networks:
  netw:
    driver: bridge

